[project]
name = "cuda2np"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "apache-tvm-ffi>=0.1.8.post2",
    "torch>=2.10.0",
]
